<?php namespace bld\ddosspelbord\Models;

use bld\ddosspelbord\helpers\hLog;
use Model;

/**
 * Model
 */
class Target_groups extends Model
{
    use \Winter\Storm\Database\Traits\Validation;

    use \Winter\Storm\Database\Traits\SoftDelete;

    protected $dates = ['deleted_at'];


    /**
     * @var string The database table used by the model.
     */
    public $table = 'bld_ddosspelbord_target_groups';

    /**
     * @var array Validation rules
     */
    public $rules = [
    ];

    /**
     * @var array Attribute names to encode and decode using JSON.
     */
    public $jsonable = [];


    public function getGroupsOptions() {
        $recs = Target_groups::orderBy('sortnr')->select('id','name')->get();
        $options = array();
        $options[''] = '(not in group)';
        foreach ($recs AS $rec) {
            $options[$rec->name] = $rec->name;
        }
        return $options;
    }

    public function afterSave()
    {
        parent::afterSave(); // TODO: Change the autogenerated stub

        if (isset($this->original['name'])) {
            hLog::logLine("D-Group old name=".$this->original['name'].", new is=$this->name, update tagerts");
            $upd = Target::where('groups',$this->original['name'])->update([
                'groups' => $this->name,
            ]);
        }

    }


}
